import {
  Activity,
  AlertCircle,
  AlertTriangle,
  Archive,
  ArrowLeft,
  ArrowRight,
  Ban,
  Bell,
  BookOpen,
  Calendar,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  CircleDot,
  Clock,
  Copy,
  CreditCard,
  Database,
  DollarSign,
  Download,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Folder,
  Gauge,
  Globe,
  Home,
  Image,
  Inbox,
  Info,
  Key,
  LayoutDashboard,
  Link as LinkIcon,
  List,
  Lock,
  LogOut,
  Mail,
  Menu,
  MessageSquare,
  MoreHorizontal,
  Package,
  Pencil,
  Plus,
  RefreshCw,
  Search,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingCart,
  Star,
  Tag,
  Trash2,
  TrendingUp,
  Upload,
  User,
  UserPlus,
  Users,
  X,
  XCircle,
  type LucideIcon,
} from 'lucide-react';
import * as React from 'react';

/**
 * Curated registry so icons stay tree-shakeable and referable by string from
 * resource metadata. Anything missing can be passed as a component instead.
 */
export const iconRegistry = {
  activity: Activity,
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  archive: Archive,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  ban: Ban,
  bell: Bell,
  'book-open': BookOpen,
  calendar: Calendar,
  check: Check,
  'check-circle': CheckCircle,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'chevrons-up-down': ChevronsUpDown,
  'circle-dot': CircleDot,
  clock: Clock,
  copy: Copy,
  'credit-card': CreditCard,
  database: Database,
  'dollar-sign': DollarSign,
  download: Download,
  eye: Eye,
  'eye-off': EyeOff,
  'file-text': FileText,
  filter: Filter,
  folder: Folder,
  gauge: Gauge,
  globe: Globe,
  home: Home,
  image: Image,
  inbox: Inbox,
  info: Info,
  key: Key,
  'layout-dashboard': LayoutDashboard,
  link: LinkIcon,
  list: List,
  lock: Lock,
  'log-out': LogOut,
  mail: Mail,
  menu: Menu,
  'message-square': MessageSquare,
  'more-horizontal': MoreHorizontal,
  package: Package,
  pencil: Pencil,
  plus: Plus,
  'refresh-cw': RefreshCw,
  search: Search,
  send: Send,
  settings: Settings,
  shield: Shield,
  'shield-check': ShieldCheck,
  'shopping-cart': ShoppingCart,
  star: Star,
  tag: Tag,
  trash: Trash2,
  'trending-up': TrendingUp,
  upload: Upload,
  user: User,
  'user-plus': UserPlus,
  users: Users,
  x: X,
  'x-circle': XCircle,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconRegistry;

/** Either a registry key or any Lucide component, so no resource needs to edit core. */
export type IconSpec = IconName | LucideIcon;

export function resolveIcon(spec: IconSpec | undefined): LucideIcon | null {
  if (!spec) return null;
  if (typeof spec === 'string') return iconRegistry[spec] ?? null;
  return spec;
}

export function Icon({
  name,
  className,
  ...props
}: { name: IconSpec | undefined } & Omit<React.ComponentProps<LucideIcon>, 'name'>) {
  const Component = resolveIcon(name);
  if (!Component) return null;
  return <Component className={className} aria-hidden {...props} />;
}
